LEADER_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes

TAP_DANCE_ENABLE = no
UNICODE_ENABLE = no
AUDIO_SUPPORTED = no
BACKLIGHT_SUPPORTED = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SWAP_HANDS_ENABLE = no
RGB_MATRIX_ENABLE = no

SRC += flow.c
SRC += layer_lock.c
SRC += source.c
